spring.application.name=Blogger Box Backend


server.port= 8080

spring.datasource.url=jdbc:postgresql://db.uckpsjfgdizrtytpbaxb.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=htxKrwPfAw5lGzVl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
